### ISSUE TITLE
Issue with turning the wheelbase off?

### ISSUE THREAD

**Issue by lshachar** [lshachar/Arduino_Fanatec_Wheel#10]
Hi guys,
I have this thing running on a CSW V2.5, and I cannot turn the wheelbase off by holding the red 'start' button. (I'm assuming it's because that the wheelbase is trying to shut the rim off before powering down, but the rim just keep repeating "Hey! I'm a rim!")

I'm wondering if anyone else has the same problem or not? and what wheelbase are you using?
Thank you.

**Comment by MagnusThome** [comment]
Do you have the USB connected to the nano board? It'll drive power back into the wheel. 

Shutting my "plus" wheel base down works.


EDIT:
I have to push the power button for 3-4 seconds to shut the base unit down

**Comment by lshachar** [comment]
usb disconnected, and I'm pushing it for even longer.
thanks for the feedback Magnus. (csl wheelbase iirc)
looking for more comments if anyone has any!

**Comment by sabifa** [comment]
Just tried it and I am able to power it off just as I'm used to with an original Fanatec rim.
I also have the csl elite + as Magnus.

**Comment by lshachar** [comment]
After reflashing the firmware (to the same, latest one) I don't have this issue anymore.
