### ISSUE TITLE
New pcb, what is the big gpio connector intended for?

### ISSUE THREAD

**Issue by MagnusThome** [lshachar/Arduino_Fanatec_Wheel#6]
Just curious if you have any specific plans using the large gpio connector that you've added to the pcb?

![gpio](https://raw.githubusercontent.com/lshachar/Arduino_Fanatec_Wheel/master/Schematics%20%26%20pcb%20layout/how%20it%20looks%20like.png)

Why I'm wondering is that the delay on using the shifter buttons currently neccesitates a separate solution for the shifter buttons.

**Comment by lshachar** [comment]
Hi Magnus!
I wanted to have a breakout board for all the gpio pins on the board... they should eventually get used for buttons, once we squash that delay bug ;)

Just like you, I'm currently using a separate solution for the shifter buttons.
